---
# tasks file for ansible-role-apache

- block:
    - name: check
      setup:
    - name: Install Apache Web Server for Redhat
      yum: name=httpd state=latest
    
  when: ansible_os_family == "RedHat"


- block:

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

  when: ansible_os_family == "Debian"

     
